// Les langues de l'appli : français et anglais. Tous les textes affichés ou dits passent par tr().
"use strict";

const LANGUES = ["fr", "en"];
let LANGUE = "fr";
try { if (LANGUES.includes(localStorage.getItem("tracto.langue"))) LANGUE = localStorage.getItem("tracto.langue"); } catch (e) { /* pas de stockage */ }

const TEXTES = {
  fr: {
    titreAccueil: "Les aventures {de}{prenom}", aucune: "Aucune histoire pour l'instant : touche « 🎤 Raconter » pour en créer une !",
    chargement: "Chargement des histoires…", astuce: "Nouvelle histoire ? Touche « 🎤 Raconter » : tu la racontes, elle se met en images toute seule.",
    images: "{n} images", illisible: "Histoire illisible", nouveau: "Nouveau", histoires: "Histoires", personnages: "Personnages",
    cestParti: "C'est parti !", encore: "Encore !", choisisVehicule: "Choisis ton véhicule", choisisCouleur: "Choisis ta couleur",
    phraseTitre: "{titre}. Choisis ton véhicule et sa couleur !", bravoBandeau: "Bravo {prenom} !",
    finHistoire: "C'est la fin de l'histoire. Bravo {prenom} !", recommence: "Bravo {prenom} ! On recommence ?", fin: "Fin !",
    oups: "Oups, cette histoire est mal écrite. On va la réparer !", langue: "English",
    bravos: ["Bravo {prenom} !", "Super, {prenom} !", "Génial, tu as réussi !", "Trop fort, {prenom} !"],
    ecole: "ÉCOLE",
    // atelier
    atelier: "L'atelier des personnages", auHasard: "Au hasard !", nouveauPerso: "+ Nouveau", renommer: "Renommer", supprimer: "Supprimer",
    atelierBienvenue: "L'atelier des personnages ! Choisis qui tu veux habiller.", promptPrenom: "Prénom du nouveau personnage ?",
    promptRenommer: "Nouveau prénom ?", confirmeSupprimer: "Supprimer {nom} ?", bonjour: "Bonjour {nom} !",
    ongletVisage: "Visage", ongletCorps: "Corps", ongletHaut: "Haut", ongletBas: "Bas", ongletPlus: "Plus",
    peau: "Peau", yeux: "Yeux", cheveux: "Cheveux", coiffure: "Coiffure : {x}", age: "Âge", enfant: "Enfant", adulte: "Adulte",
    taille: "Taille", petit: "Petit", moyen: "Moyen", grand: "Grand", corpulence: "Corpulence",
    mince: "Mince", costaud: "Costaud", rond: "Rond", haut: "Haut : {x}", couleurHaut: "Couleur du haut",
    dessinHaut: "Dessin sur le haut : {x}", aucun: "aucun", aucunMaj: "Aucun", bas: "Bas", basAvec: "Bas : avec une {x}, la couleur suffit",
    pantalon: "Pantalon", short: "Short", jupe: "Jupe", collant: "Collant (ou jambes nues)", couleurBas: "Couleur du bas",
    chaussures: "Chaussures", accessoires: "Accessoires", lunettes: "Lunettes", couronne: "Couronne", cils: "Cils",
    moustache: "Moustache", barbe: "Barbe", nu: "nu", enregistre: "✓ Enregistré sur cet appareil",
    gardes: "Les changements sont gardés sur cet appareil",
    coiffures: { court: "Court", herisse: "En pics", boucle: "Bouclés", milong: "Mi-longs", long: "Longs", couettes: "Couettes", chignon: "Chignon", chauve: "Dégarni" },
    dessins: { tractopelle: "Tractopelle", dino: "Dinosaure", etoile: "Étoile", coeur: "Cœur" },
    hauts: { teeshirt: "Tee-shirt", pull: "Pull", chemise: "Chemise", debardeur: "Débardeur", salopette: "Salopette", robe: "Robe" },
    // écrire une histoire dans l'appli
    ecrire: "Écrire", ecrireTitre: "Écrire une histoire", mesHistoires: "Mes histoires", nouvelleHistoire: "+ Nouvelle histoire",
    aucuneMienne: "Pas encore d'histoire : crée la première !", titreHistoire: "Titre", vehicule: "Véhicule", couleur: "Couleur",
    scenes: "Les scènes", ajouterScene: "+", lieu: "Où ?", action: "Que se passe-t-il ?", quiEstLa: "Qui est là ?",
    toucher: "{prenom} touche l'écran ?", oui: "Oui", non: "Non", texte: "Le texte", monTexte: "Mon texte", texteAuto: "Texte auto",
    supprimerScene: "Enlever la scène", essayer: "▶ Essayer", supprimerHistoire: "Supprimer", gardeAppareil: "Gardé sur cet appareil",
    titreDefaut: "Mon histoire", promptTitre: "Titre de l'histoire ?", promptTexte: "Écris le texte de cette scène (pour enfants) :",
    promptTexteEn: "Version anglaise (facultatif) :", confirmeSupprimerHistoire: "Supprimer « {titre} » ?", maxScenes: "300 scènes maximum",
    refuse: "Ce texte n'est pas accepté : {raison}", moi: "Moi",
    ongletOuQuoi: "Où & quoi", ongletQui: "Qui", ongletToucher: "Toucher", chapitre: "Chapitre", phraseChapitre: "Chapitre {n} : {titre}", chapitresN: "{n} chapitres", minutes: "{n} min",
    commencerChapitre: "Commencer au chapitre :", finiBouton: "✅ C'est fini !", herosMot: "⭐ Héros de l'histoire",
    interTitre: "Est-ce que {prenom} touche l'écran pendant l'histoire ?", interOui: "👆 Oui, {prenom} touche l'écran", interNon: "📺 Non, on regarde et on écoute",
    interAide: "Oui : aux moments d'action (toboggan, gâteau, pont…), {prenom} touche l'écran pour faire avancer l'histoire. Non : l'histoire se déroule toute seule.", verrouAstuce: "🔒 Pour les parents : garde le doigt appuyé sur le bouton",
    raconter: "🎤 Raconter", dicteeTitre: "🎤 Raconte ton histoire",
    dicteeAide: "Appuie sur le micro et raconte ton histoire, comme tu la dirais. Les « euh » et les répétitions s'enlèvent tout seuls. Dis « chapitre » pour commencer un chapitre. Quand tu as fini, touche « C'est fini ! ».",
    dicteeGo: "🎤 Appuie et raconte", dicteeStop: "⏹ J'ai fini", dicteeIndispo: "La dictée n'est pas disponible ici : utilise le micro 🎤 du clavier pour dicter.",
    narrBouton: "🎙 Raconter avec ma voix", narrEnreg: "🎤 Enregistrer", narrRefaire: "🎤 Refaire", narrStop: "⏹ Arrêter ({s} s)",
    narrEcoute: "▶ Écouter", narrEfface: "🗑 Effacer", narrFini: "✓ Terminé", narrEcran: "Écran {i} / {n}",
    narrAide: "Lis le texte, puis touche 🎤 : ta voix remplacera celle de l'appli.", narrCompte: "🎙 {n} écran(s) avec ta voix",
    miniTitre: "Choisis l'image de l'histoire", miniAuto: "Auto",
    miniBouton: "🖼 Miniature", miniEditeur: "🖼 Personnalise la miniature", ongFond: "Fond", ongImages: "Images", ongBande: "Bandeau",
    fondAucun: "Aucun", fondPhoto: "📷 Photo", miniDefaut: "↺ Par défaut", miniFini: "✓ Terminé", bandeAuto: "Auto",
    miniAide: "Fais glisser les images dans le cadre orange. Touche une image pour la régler.",
    partager: "📤 Envoyer", recevoir: "📥 Recevoir", importOk: "Histoire reçue : « {titre} »",
    importErreur: "Ce fichier n'est pas une histoire Tracto.", importRefus: "Histoire refusée : {raison}",
    consigneAddition: "Combien ça fait ? Touche la bonne réponse !", motMot: "Mot à écrire :", promptMot: "Le mot que l'enfant doit écrire (ex. : son prénom) :", chapNouveau: "+ 📖 Nouveau chapitre", chapIci: "✂ Chapitre ici", chapPas: "Pas encore de chapitres : découpe ton histoire avec les boutons à droite →", chapitreIci: "📖 Nouveau chapitre ici", chapitreNom: "📖 Chapitre {n} : {titre}",
    promptChapitre: "Titre du chapitre (ex. : « L'orage dans la forêt ») :", promptChapitreEn: "Titre en anglais (facultatif) :", objetMot: "On cherche :",
    objets: { ballon: "Ballon", doudou: "Doudou", cle: "Clé", chat: "Moustache" },
    ongletTexte: "Texte", ongletPlus: "Plus", ongletPlacer: "🎨 Écran",
    naissance: "🎂 Date de naissance", promptNaissance: "Date de naissance (JJ/MM/AAAA) :", ageAns: "{n} ans", naissanceVide: "Ajouter",
    naissanceAide: "Sert à adapter les jeux (compter, lettres) à son âge.",
    catPerso: "Personnages", catEngins: "Engins", catObjets: "Objets", dupliquer: "⧉ Dupliquer",
    composerAide: "Touche une image à droite pour l'ajouter, puis fais-la glisser avec le doigt.",
    composerLibre: "« ✨ Libre » (onglet Où & quoi) : l'écran ne montre que ce que tu y poses.",
    toucherOui: "⭐ {prenom} devra toucher cette image.", toucherNon: "Cette image n'est plus à toucher.",
    meteo: "Météo", meteos: { aucune: "Aucune", pluie: "🌧 Pluie", neige: "❄ Neige", arcenciel: "🌈 Arc-en-ciel", etoiles: "✨ Étoiles filantes", orage: "⛈ Orage" },
    bulleMot: "Bulle : qui parle ?", bulleAucune: "Personne", bulleEcrire: "💬 Écrire", bulleEffacer: "Effacer",
    promptBulle: "Ce que {qui} dit (une petite phrase) :", promptBulleEn: "En anglais (facultatif) :",
    voixMot: "Ta voix pour cette scène (elle remplace la voix de l'appli)", enregistrer: "🎤 Enregistrer", arreter: "⏹ Arrêter ({s} s)",
    ecouter: "▶ Écouter", effacerVoix: "🗑 Effacer", voixOk: "Voix enregistrée ✓", microRefuse: "Micro indisponible : autorise-le dans les réglages.",
    placerAide: "Choisis quelqu'un, puis touche l'image là où il doit aller.", placerAuto: "Places auto", placerPersonne: "Personne dans cette scène (onglet « Qui »).",
    moment: "Moment", jour: "Jour", nuitMot: "Nuit", humeurMot: "Humeur", humAuto: "Auto", humJoie: "Joyeux", humCalme: "Calme", humPeur: "Inquiet",
    enginsCopains: "Engins copains", combien: "Combien de fois ?", phraseConsigne: "Ce qu'on lui dit de faire", maPhrase: "Ma phrase",
    phraseAuto: "Phrase auto", promptConsigne: "Phrase pour dire à l'enfant quoi faire (ex. : « Touche le camion ! ») :",
    guidee: "+ Guidée", texteLibreBouton: "📝 Texte libre", astuceLibre: "Astuce : « 📝 Texte libre » pour écrire toute l'histoire d'un coup.",
    libreTitre: "Écris ton histoire", libreAide: "Une ligne = une image (300 maximum). Écris « touche » là où {prenom} doit toucher l'écran. Une ligne « Papa : On y va ! » fait parler Papa dans une bulle. Le bouton « 📖 Nouveau chapitre » coupe l'histoire en chapitres. Les lieux, les actions et les personnages sont reconnus tout seuls.",
    libreCreer: "Créer l'histoire", libreAnnuler: "Annuler", libreVide: "Écris au moins une phrase.", libreTrop: "300 lignes maximum : les suivantes sont ignorées.",
    libreLigne: "Ligne {n} : {raison}", libreTitrePlace: "Titre de l'histoire",
    libreExemple: "📖 Le départ\nArthur part au chantier avec Papa.\nOh ! Un gros trou sur la route. Touche pour le remplir !\nPapa : On va le remplir ensemble !\nLes copains arrivent pour aider.\nHourra, on fait la fête !",
    supprimerBouton: "✕ Supprimer", termine: "✓ Terminé", remettre: "Remettre les histoires retirées ({n})",
    toucheCroix: "Touche la croix rouge d'une histoire pour la supprimer.",
    confirmePerso: "Supprimer « {titre} » pour toujours ?", confirmeCachee: "Retirer « {titre} » de cet appareil ? (tu pourras la remettre)",
    filtreLong: "il est trop long ({n} lettres maximum).", filtreLien: "pas de lien internet.", filtreEmail: "pas d'adresse e-mail.",
    filtreNumero: "pas de numéro de téléphone.", filtreMot: "« {mot} » n'est pas un mot pour les enfants.",
    lieux: { chantier: "Chantier", ville: "Ville", campagne: "Campagne", jardin: "Jardin", ecole: "École", vacances: "Vacances", plage: "Plage", neige: "Neige", dinosaures: "Dinos", foret: "Forêt", montagne: "Montagne", ferme: "Ferme", port: "Port" },
    actions: { rouler: "Rouler", parler: "Discuter", trou: "Trou", feu: "Feu", deblayer: "Sable", construire: "Maison", copains: "Copains", manger: "Manger", spectacle: "Spectacle", bulles: "Bulles", calin: "Câlin", piscine: "Piscine", cueillir: "Mûres", chateau: "Château", route: "Route", voler: "S'envoler", fenetres: "Fenêtres", cadeau: "Cadeau", velo: "Vélo", libre: "✨ Libre", chiffres: "Compter", lettres: "Lettres", pont: "Pont", arbre: "Arbre tombé", panne: "Panne", chercher: "Cache-cache", fete: "Fête", dormir: "Dodo" },
    // véhicules et couleurs (pour {heros}, {vehicule}, {couleur})
    vehicules: { tractopelle: ["le tractopelle", "m"], benne: ["le camion benne", "m"], toupie: ["le camion toupie", "m"], pompier: ["le camion de pompiers", "m"], bulldozer: ["le bulldozer", "m"], grue: ["la grue", "f"] },
    couleurs: { jaune: "jaune", orange: "orange", rouge: "rouge", bleu: "bleu", vert: "vert", violet: "violet", rose: "rose" },
    couleursF: { bleu: "bleue", vert: "verte", violet: "violette" },
  },
  en: {
    titreAccueil: "{prenom}'s adventures", aucune: "No stories yet: tap “🎤 Tell” to make one!",
    chargement: "Loading stories…", astuce: "A new story? Tap “🎤 Tell”: you tell it, it turns into pictures by itself.",
    images: "{n} pictures", illisible: "Unreadable story", nouveau: "New", histoires: "Stories", personnages: "Characters",
    cestParti: "Let's go!", encore: "Again!", choisisVehicule: "Choose your vehicle", choisisCouleur: "Choose your color",
    phraseTitre: "{titre}. Choose your vehicle and its color!", bravoBandeau: "Well done {prenom}!",
    finHistoire: "That's the end of the story. Well done, {prenom}!", recommence: "Well done {prenom}! Shall we play again?", fin: "The End!",
    oups: "Oops, this story has a mistake in it. We will fix it!", langue: "Français",
    bravos: ["Well done, {prenom}!", "Super, {prenom}!", "Great, you did it!", "Amazing, {prenom}!"],
    ecole: "SCHOOL",
    atelier: "The character workshop", auHasard: "Surprise me!", nouveauPerso: "+ New", renommer: "Rename", supprimer: "Delete",
    atelierBienvenue: "The character workshop! Choose who you want to dress up.", promptPrenom: "New character's first name?",
    promptRenommer: "New first name?", confirmeSupprimer: "Delete {nom}?", bonjour: "Hello {nom}!",
    ongletVisage: "Face", ongletCorps: "Body", ongletHaut: "Top", ongletBas: "Bottom", ongletPlus: "More",
    peau: "Skin", yeux: "Eyes", cheveux: "Hair", coiffure: "Hairstyle: {x}", age: "Age", enfant: "Child", adulte: "Adult",
    taille: "Height", petit: "Short", moyen: "Medium", grand: "Tall", corpulence: "Build",
    mince: "Slim", costaud: "Strong", rond: "Round", haut: "Top: {x}", couleurHaut: "Top color",
    dessinHaut: "Picture on the top: {x}", aucun: "none", aucunMaj: "None", bas: "Bottom", basAvec: "Bottom: with a {x}, just pick the color",
    pantalon: "Pants", short: "Shorts", jupe: "Skirt", collant: "Tights (or bare legs)", couleurBas: "Bottom color",
    chaussures: "Shoes", accessoires: "Accessories", lunettes: "Glasses", couronne: "Crown", cils: "Lashes",
    moustache: "Moustache", barbe: "Beard", nu: "bare", enregistre: "✓ Saved on this device",
    gardes: "Changes are saved on this device",
    coiffures: { court: "Short", herisse: "Spiky", boucle: "Curly", milong: "Mid-length", long: "Long", couettes: "Pigtails", chignon: "Bun", chauve: "Balding" },
    dessins: { tractopelle: "Backhoe", dino: "Dinosaur", etoile: "Star", coeur: "Heart" },
    hauts: { teeshirt: "T-shirt", pull: "Sweater", chemise: "Shirt", debardeur: "Tank top", salopette: "Overalls", robe: "Dress" },
    ecrire: "Write", ecrireTitre: "Write a story", mesHistoires: "My stories", nouvelleHistoire: "+ New story",
    aucuneMienne: "No story yet: create the first one!", titreHistoire: "Title", vehicule: "Vehicle", couleur: "Color",
    scenes: "Scenes", ajouterScene: "+", lieu: "Where?", action: "What happens?", quiEstLa: "Who's there?",
    toucher: "Does {prenom} tap the screen?", oui: "Yes", non: "No", texte: "The text", monTexte: "My text", texteAuto: "Auto text",
    supprimerScene: "Remove scene", essayer: "▶ Try it", supprimerHistoire: "Delete", gardeAppareil: "Saved on this device",
    titreDefaut: "My story", promptTitre: "Story title?", promptTexte: "Write this scene's text in French (for children):",
    promptTexteEn: "English version (optional):", confirmeSupprimerHistoire: "Delete “{titre}”?", maxScenes: "300 scenes maximum",
    refuse: "This text isn't allowed: {raison}", moi: "Mine",
    ongletOuQuoi: "Where & what", ongletQui: "Who", ongletToucher: "Tap", chapitre: "Chapter", phraseChapitre: "Chapter {n}: {titre}", chapitresN: "{n} chapters", minutes: "{n} min",
    commencerChapitre: "Start at chapter:", finiBouton: "✅ I'm done!", herosMot: "⭐ Story hero",
    interTitre: "Does {prenom} tap the screen during the story?", interOui: "👆 Yes, {prenom} taps the screen", interNon: "📺 No, we just watch and listen",
    interAide: "Yes: at action moments (slide, cake, bridge…), {prenom} taps the screen to move the story along. No: the story plays by itself.", verrouAstuce: "🔒 For grown-ups: keep your finger on the button",
    raconter: "🎤 Tell", dicteeTitre: "🎤 Tell your story",
    dicteeAide: "Tap the microphone and tell your story the way you would say it. “Um”s and repeats are removed automatically. Say “chapter” to start a chapter. When you're done, tap “I'm done!”.",
    dicteeGo: "🎤 Tap and talk", dicteeStop: "⏹ I'm done", dicteeIndispo: "Dictation isn't available here: use the keyboard's 🎤 microphone to dictate.",
    narrBouton: "🎙 Narrate with my voice", narrEnreg: "🎤 Record", narrRefaire: "🎤 Redo", narrStop: "⏹ Stop ({s} s)",
    narrEcoute: "▶ Listen", narrEfface: "🗑 Delete", narrFini: "✓ Done", narrEcran: "Screen {i} / {n}",
    narrAide: "Read the text, then tap 🎤: your voice will replace the app's voice.", narrCompte: "🎙 {n} screen(s) with your voice",
    miniTitre: "Choose the story's picture", miniAuto: "Auto",
    miniBouton: "🖼 Thumbnail", miniEditeur: "🖼 Customize the thumbnail", ongFond: "Background", ongImages: "Pictures", ongBande: "Banner",
    fondAucun: "None", fondPhoto: "📷 Photo", miniDefaut: "↺ Default", miniFini: "✓ Done", bandeAuto: "Auto",
    miniAide: "Drag the pictures inside the orange frame. Tap a picture to adjust it.",
    partager: "📤 Send", recevoir: "📥 Receive", importOk: "Story received: “{titre}”",
    importErreur: "This file isn't a Tracto story.", importRefus: "Story refused: {raison}",
    consigneAddition: "What's the answer? Tap it!", motMot: "Word to spell:", promptMot: "The word the child must spell (e.g. their name):", chapNouveau: "+ 📖 New chapter", chapIci: "✂ Chapter here", chapPas: "No chapters yet: split your story with the buttons on the right →", chapitreIci: "📖 New chapter here", chapitreNom: "📖 Chapter {n}: {titre}",
    promptChapitre: "Chapter title, in French (e.g. “L'orage dans la forêt”):", promptChapitreEn: "Title in English (optional):", objetMot: "Looking for:",
    objets: { ballon: "Ball", doudou: "Teddy", cle: "Key", chat: "Whiskers" },
    ongletTexte: "Text", ongletPlus: "More", ongletPlacer: "🎨 Screen",
    naissance: "🎂 Date of birth", promptNaissance: "Date of birth (DD/MM/YYYY):", ageAns: "{n} years old", naissanceVide: "Add",
    naissanceAide: "Used to adapt the games (counting, letters) to their age.",
    catPerso: "Characters", catEngins: "Trucks", catObjets: "Things", dupliquer: "⧉ Duplicate",
    composerAide: "Tap a picture on the right to add it, then drag it with your finger.",
    composerLibre: "“✨ Free” (Where & what tab): the screen only shows what you put on it.",
    toucherOui: "⭐ {prenom} will have to tap this picture.", toucherNon: "This picture no longer needs a tap.",
    meteo: "Weather", meteos: { aucune: "None", pluie: "🌧 Rain", neige: "❄ Snow", arcenciel: "🌈 Rainbow", etoiles: "✨ Shooting stars", orage: "⛈ Storm" },
    bulleMot: "Speech bubble: who's talking?", bulleAucune: "Nobody", bulleEcrire: "💬 Write", bulleEffacer: "Clear",
    promptBulle: "What {qui} says, in French (a short sentence):", promptBulleEn: "In English (optional):",
    voixMot: "Your voice for this scene (replaces the app's voice)", enregistrer: "🎤 Record", arreter: "⏹ Stop ({s} s)",
    ecouter: "▶ Listen", effacerVoix: "🗑 Delete", voixOk: "Voice recorded ✓", microRefuse: "Microphone unavailable: allow it in settings.",
    placerAide: "Pick someone, then tap the picture where they should go.", placerAuto: "Auto places", placerPersonne: "Nobody in this scene (“Who” tab).",
    moment: "Time of day", jour: "Day", nuitMot: "Night", humeurMot: "Mood", humAuto: "Auto", humJoie: "Happy", humCalme: "Calm", humPeur: "Worried",
    enginsCopains: "Truck friends", combien: "How many taps?", phraseConsigne: "What we tell him to do", maPhrase: "My sentence",
    phraseAuto: "Auto sentence", promptConsigne: "Sentence telling the child what to do (e.g. “Tap the truck!”), in French:",
    guidee: "+ Guided", texteLibreBouton: "📝 Free text", astuceLibre: "Tip: “📝 Free text” lets you write the whole story at once.",
    libreTitre: "Write your story", libreAide: "One line = one picture (300 max). A line like “Papa : On y va !” makes Daddy speak in a bubble. The “📖 New chapter” button splits the story into chapters. Write “touche” (tap) where {prenom} must tap the screen. Places, actions and characters are recognized automatically (in French).",
    libreCreer: "Create story", libreAnnuler: "Cancel", libreVide: "Write at least one sentence.", libreTrop: "300 lines maximum: the rest is ignored.",
    libreLigne: "Line {n}: {raison}", libreTitrePlace: "Story title",
    libreExemple: "📖 Le départ\nArthur part au chantier avec Papa.\nOh ! Un gros trou sur la route. Touche pour le remplir !\nPapa : On va le remplir ensemble !\nLes copains arrivent pour aider.\nHourra, on fait la fête !",
    supprimerBouton: "✕ Delete", termine: "✓ Done", remettre: "Bring back removed stories ({n})",
    toucheCroix: "Tap a story's red cross to delete it.",
    confirmePerso: "Delete “{titre}” forever?", confirmeCachee: "Remove “{titre}” from this device? (you can bring it back)",
    filtreLong: "it's too long ({n} letters maximum).", filtreLien: "no web links.", filtreEmail: "no email addresses.",
    filtreNumero: "no phone numbers.", filtreMot: "“{mot}” isn't a word for children.",
    lieux: { chantier: "Building site", ville: "Town", campagne: "Countryside", jardin: "Backyard", ecole: "School", vacances: "Vacation", plage: "Beach", neige: "Snow", dinosaures: "Dinos", foret: "Forest", montagne: "Mountains", ferme: "Farm", port: "Harbor" },
    actions: { rouler: "Drive", parler: "Chat", trou: "Hole", feu: "Fire", deblayer: "Sand", construire: "House", copains: "Friends", manger: "Eat", spectacle: "Show", bulles: "Bubbles", calin: "Hug", piscine: "Pool", cueillir: "Berries", chateau: "Sandcastle", route: "Road", voler: "Fly", fenetres: "Windows", cadeau: "Present", velo: "Bike", fete: "Party", dormir: "Sleep", libre: "✨ Free", chiffres: "Count", lettres: "Letters", pont: "Bridge", arbre: "Fallen tree", panne: "Breakdown", chercher: "Hide & seek" },
    vehicules: { tractopelle: ["the backhoe", "m"], benne: ["the dump truck", "m"], toupie: ["the cement mixer", "m"], pompier: ["the fire truck", "m"], bulldozer: ["the bulldozer", "m"], grue: ["the crane", "f"] },
    couleurs: { jaune: "yellow", orange: "orange", rouge: "red", bleu: "blue", vert: "green", violet: "purple", rose: "pink" },
    couleursF: {},
  },
};
const CONSIGNES_EN = {
  trou: "Tap to fill the hole!", feu: "Tap to spray the fire!", deblayer: "Tap to push the sand!",
  construire: "Tap to build the house!", copains: "Tap to call your friends!", manger: "Tap to feed them!",
  spectacle: "Tap to make the trucks jump!", bulles: "Tap to blow bubbles!", calin: "Tap for a big hug!",
  piscine: "Tap to jump in the pool!", cueillir: "Tap to pick the blackberries!", chateau: "Tap to build a sandcastle!",
  route: "Tap to lay the stones!", voler: "Tap to fly higher!", fenetres: "Tap to fit the windows!",
  cadeau: "Tap to open the present!", velo: "Tap to pedal higher!", fete: "Tap to launch the fireworks!",
  dormir: "Tap to light up the stars!", rouler: "Tap to honk!", parler: "Tap to honk!",
  pont: "Tap to lay the bridge planks!", arbre: "Tap to push the tree!", panne: "Tap to fix the truck!", chercher: "Tap the bushes to search!",
  libre: "Tap the sparkling picture!", chiffres: "Tap the numbers in order!", lettres: "Tap the letters in order!",
};

function tr(cle, vars = {}) { // texte dans la langue choisie (repli : français)
  const v = TEXTES[LANGUE][cle] ?? TEXTES.fr[cle] ?? cle;
  return typeof v === "string" ? v.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? vars[k] : m)) : v;
}
function changeLangue(l) {
  LANGUE = l;
  try { localStorage.setItem("tracto.langue", l); } catch (e) { /* pas de stockage */ }
}
